<div class="cp-app-container" data-app="affiliates-settings">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                <?php echo cl_translate('Affiliates settings'); ?>
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        <?php echo cl_translate('Control panel'); ?>
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        <?php echo cl_translate('Affiliates settings'); ?>
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        <?php echo cl_translate('Manage affiliates system settings'); ?>
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="aff_bonus_rate-input">
                                    <label>
                                        <?php echo cl_translate('Affiliate bonus rate'); ?>
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config aff_bonus_rate%}" name="aff_bonus_rate" type="text" class="form-control" placeholder="E. g. 0.50">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group" data-an="affiliates_system-input">
                                    <label>
                                        <?php echo cl_translate('Affiliates System'); ?>
                                    </label>
                                    <div class="form-line">
                                        <select name="affiliates_system" class="form-control selectpicker">
                                            <option value="on" <?php if($cl['config']['affiliates_system'] == 'on') { echo('selected'); } ?>>
                                                <?php echo cl_translate('Enabled'); ?>
                                            </option>
                                            <option value="off" <?php if($cl['config']['affiliates_system'] == 'off') { echo('selected'); } ?>>
                                                <?php echo cl_translate('Disabled'); ?>
                                            </option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg waves-effect ttup">
                                    <?php echo cl_translate("Save changes"); ?>
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo cl_template('cpanel/assets/affiliate_settings/scripts/app_master_script'); ?>