<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		<?php echo fetch_or_get($cl["page_title"],$cl["config"]["title"]); ?>
	</title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>"/>
    <meta name="description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>"/>
    <meta name="keywords" content="<?php echo fetch_or_get($cl['page_kw'], $cl["config"]["keywords"]);?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	
	<?php if ($cl["pn"] == 'thread'): ?>
		<meta property="og:type" content="article" />
		<meta property="og:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>"/>
		<meta property="og:image:secure_url" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
		<meta property="og:description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
		<meta property="og:title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
		<meta property="og:url" content="<?php echo fetch_or_get($cl["page_url"], $cl["config"]["url"]); ?>" />
		<meta name="twitter:card" content="summary">
		<meta name="twitter:title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
		<meta name="twitter:description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
		<meta name="twitter:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
	<?php endif ?>

	<?php if (in_array($cl["pn"], array("profile", "connections"))): ?>
		<?php if ($cl['prof_user']['index_privacy'] == 'N'): ?>
		    <meta name="robots" content="noindex">
		    <meta name="googlebot" content="noindex">
	    <?php endif; ?>
    <?php endif; ?>

	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/bootstrap-v4.0.0.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/animate.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/md-checkbox.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/emojionearea.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/preloader.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/material_icon_fonts/material_icon.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.master.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.mq.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.custom.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/jquery.fancybox.css?v={%config version%}">
	<link rel="icon" href="{%config site_favicon%}" type="image/png">

	<script src="{%config theme_url%}/statics/js/libs/jquery-3.5.1.min.js?v={%config version%}"></script>
	<?php if ($cl["server_mode"] == 'development'): ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.dev.min.js?v={%config version%}"></script>
	<?php else: ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.min.js?v={%config version%}"></script>
	<?php endif; ?>
	
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/validators.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/vuelidate.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.form-v4.2.2.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/popper.1.12.9.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/bootstrap.v4.0.0.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/afterglow/afterglow.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/sticky-sidebar/source/jquery.sticky-sidebar.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/master.script.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/custom.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/emojionearea.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/clipboard.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.fancybox.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/lozad.min.js"></script>
</head>
<body class="cl-app-<?php echo fetch_or_get($cl["pn"], "none"); ?>">
	<div class="main-preloader-holder" id="main-preloader-holder">
		<div class="main-preloader">
			<div class="loading">
				<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
			</div>
		</div>
	</div>
	<div data-el="main-content-holder">
		<main class="main-content-container <?php echo (($cl["is_logged"]) ? "" : "guest-mode" ); ?>">
			<div class="main-content-container-inner">
				<?php if (not_empty($cl["sbl"])): ?>
					<?php if (not_empty($cl["is_logged"])): ?>
						<?php echo cl_template('main/left_sidebar'); ?>
					<?php else: ?>
						<?php echo cl_template('main/left_sidebar_guest'); ?>
					<?php endif; ?>
				<?php endif; ?>

				<div data-el="timeline-container-wrapper" class="timeline-container-wrapper">
					<div data-el="timeline-content" class="timeline-container-inner">
						<?php echo $cl["http_res"]; ?>
					</div>

					<div data-el="spa-preloader" class="spa-preloader d-none">
						<div class="spa-preloader-inner">
							<span class="spinner-icon">
								<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve"><path opacity="0.6" fill="#1ca1f3" d="M20.201,5.169c-8.254,0-14.946,6.692-14.946,14.946c0,8.255,6.692,14.946,14.946,14.946 s14.946-6.691,14.946-14.946C35.146,11.861,28.455,5.169,20.201,5.169z M20.201,31.749c-6.425,0-11.634-5.208-11.634-11.634 c0-6.425,5.209-11.634,11.634-11.634c6.425,0,11.633,5.209,11.633,11.634C31.834,26.541,26.626,31.749,20.201,31.749z"></path><path fill="#1ca1f3" d="M26.013,10.047l1.654-2.866c-2.198-1.272-4.743-2.012-7.466-2.012h0v3.312h0 C22.32,8.481,24.301,9.057,26.013,10.047z" transform="rotate(299.57 20 20)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 20 20" to="360 20 20" dur="0.7s" repeatCount="indefinite"></animateTransform></path></svg>
							</span>
						</div>
					</div>
				</div>

				<?php if (not_empty($cl["sbr"])): ?>
					<?php echo cl_template('main/right_sidebar'); ?>
				<?php endif; ?>
			</div>
		</main>

		<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
			<?php echo cl_template('main/bottom_navbar'); ?>
		<?php endif; ?>

		<input id="csrf-token" type="hidden" class="hidden d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>">

		<?php if ($cl['is_logged']): ?>
			<div class="modal fadeIn vh-center modal-pubbox" data-app="modal-pubbox" id="add_new_post" tabindex="-1" role="dialog" aria-hidden="true">
			    <div class="modal-dialog" role="document">
			        <div class="modal-content">
			            <div class="modal-header">
			                <div class="main---mh--block">
			                    <h5 class="modal-title"><?php echo cl_translate('New post'); ?></h5>
			                    <span class="dismiss-modal" data-dismiss="modal">
			                        <?php echo cl_svg('md-close'); ?>
			                    </span>
			                </div>
			            </div>
			            <div class="modal-body">
			                <?php $cl['pb_id'] = 2; echo cl_template('timeline/pubbox'); ?>
			            </div>
			        </div>
			    </div>
			</div>
			<?php echo cl_template('timeline/scripts/pubbox_master_script'); ?>	
		<?php endif; ?>

		<?php if ($cl["pn"] != 'guest'): ?>
			<?php echo cl_template("main/scripts/app_master_script"); ?>
		<?php endif; ?>

		<div data-app="black-hole"></div>

		<?php if (not_empty($cl['config']['google_analytics'])): ?>
			<?php echo htmlspecialchars_decode($cl['config']['google_analytics']); ?>
		<?php endif; ?>
	</div>
</body>
</html>

