<tr>
    <td colspan="7">
        <div class="empty-table">
            <span class="icon">
                <i class="material-icons">group</i>
            </span>
            <h4><?php echo('No users found'); ?></h4>
            <p>
                <?php echo('It looks like there are no users in your database yet. All users of your site will be displayed here.'); ?>
            </p>
        </div>
    </td>
</tr>