<tr>
    <td colspan="8">
        <div class="empty-table">
            <span class="icon">
                <i class="material-icons">group</i>
            </span>
            <h4><?php echo("No reports found"); ?></h4>
            <p>
                <?php echo("It looks like there are no account reports in your database yet. All of your site's account reports will be displayed here."); ?>
            </p>
        </div>
    </td>
</tr>