<h2 id="get-characters">User profile data</h2>
<p>
    Please use this API to access user profile data fetching endpoint
</p>
<br>
<h4 class="table-title">Get parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>user_id</td>
            <td>Profile user ID</td>
            <td>
                In order to get information about the profile, you must send a valid ID
            </td>
        </tr>
        <tr>
            <td>session_id</td>
            <td>User auth token (Optional)</td>
            <td>
                In this case, authorization is not required, but it is desirable to determine whether you are subscribed to this profile or not, blocked or not, etc.
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
"code": 200,
"message": "Profile fetched successfully",
"data": {
        "posts": [...],
        "media": [...],
        "likes": [...],
        "user": {
            "id": 7,
            "first_name": "Dan",
            "last_name": "Kassing",
            "user_name": "dan_kassing",
            "email": "ibragimov.ahmat.tl@gmail.com",
            "is_verified": true,
            "website": "",
            "about_you": "",
            "gender": "M",
            "country": "United States",
            "post_count": 4045,
            "last_post": 0,
            "last_ad": 0,
            "wallet": "323.34",
            "about": "",
            "ip_address": "127.0.0.1",
            "following_count": 1,
            "follower_count": 3512,
            "language": "english",
            "last_active": "1601401610",
            "profile_privacy": "followers",
            "member_since": "Jul 2020",
            "is_blocked_visitor": false,
            "is_following": false,
            "can_view_profile": false
        }
    }
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 404,
    "message": "Profile with this ID does not exist",
    "data": []
}
</code></pre>
    </div>
</div>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 400,
    "message": "Invalid request data",
    "data": []
}
</code></pre>
    </div>
</div>