<!--
Attention, this markup template is not part of the interface as such, 
but is used by this system to send an emails to the users, 
and that is why this file contains linine CSS styles
-->
<div style="background: #fff; border-radius: 5px; border:1px solid #eee; padding: 30px 50px;">
	<h3 style="padding: 0px; margin: 0 0 15px 0; font-size: 24px; line-height: 24px; color: #192a32;">
		<?php echo cl_translate("Hello"); ?>: <b><?php echo($cl["me"]["name"]); ?></b>,
	</h3>
	<p style="padding: 0; margin: 0 0 30px 0; font-size: 16px; color: #666;">
		<?php echo cl_translate("Tap the botton below to reset your account password. If you did not request a new password, you can safely delete this email."); ?>:
	</p>
	<div style="width: 100%; margin-bottom: 30px;">
		<a href="<?php echo ($cl['reset_url']); ?>" style="color: #fff; text-decoration: none; background: #1ca1f3; padding: 15px 30px; border-radius: 5px; border: 1px solid #1ca1f3; font-size: 13px; line-height: 13px;">
			<?php echo cl_translate("Reset my password"); ?>
		</a>
	</div>
	<p style="font-size: 12px; color: #999;">
		<span>
			{%config name%} - <?php echo cl_translate("Support team"); ?>.
		</span>
	</p>
</div>