<div class="timeline-container" data-app="blocked">
	<div class="timeline-header">
		<div class="lp">
			<div class="nav-link-holder">
				<a href="<?php echo cl_link("blocked"); ?>" data-spa="true">
					<?php echo cl_translate('You are blocked!'); ?>
				</a>
			</div>
		</div>
		<div class="cp">
			<a href="<?php echo cl_link('/'); ?>">
				<img src="{%config site_logo%}" alt="Logo">
			</a>
		</div>
		<div class="rp">
			<div class="nav-link-holder">
				<span class="go-back" onclick="SMColibri.jump_back(-2);">
					<?php echo cl_svg('md-arrow-back'); ?>
				</span>
			</div>
		</div>
	</div>

	<div class="user-blocked-page">
		<div class="icon">
			<?php echo cl_svg('sad-outline'); ?>
		</div>
		<div class="pl-message">
			<h4>
				<?php echo cl_translate('You are blocked!'); ?>
			</h4>
			<p>
				<?php echo cl_translate("Sorry, access to this profile is denied! You have been blocked by this user"); ?>
			</p>
		</div>
		<div class="c2action-single">
			<a href="<?php echo cl_link('/'); ?>">
				<button class="btn btn-custom main-outline lg">
					<?php echo cl_translate("Go to your feed"); ?>
				</button>
			</a>
		</div>
	</div>

	<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
</div>