<script>
	"use strict";

	jQuery(document).ready(function($) {
		var _app = $('div[data-app="connections"]');

		_app.find('button[data-an="load-more"]').on('click', function(event) {
			event.preventDefault();
			var people_ls = _app.find('div[data-an="connectivity-list"]');
			var last_li   = people_ls.find('div[data-list-item]').last();
			var _self     = $(this);

			if (last_li.length) {
				$.ajax({
					url: "<?php echo cl_link("native_api/connections/load_more"); ?>",
					type: 'GET',
					dataType: 'json',
					data: {
						offset: last_li.data('list-item'),
						type: "<?php echo($cl['page_tab']); ?>",
						prof_id: "<?php echo($cl['prof_user']['id']); ?>",
					},
					beforeSend: function(){
						_self.attr('disabled', 'true').text("<?php echo cl_translate("Please wait"); ?>");
					}
				}).done(function(data) {
					if (data.status == 200) {
						people_ls.append(data.html);

						_self.removeAttr('disabled').text("<?php echo cl_translate("Show more"); ?>");
					}

					else {
						_self.text("<?php echo cl_translate("That is all for now!"); ?>");
					}
				});
			}
		});
	});
</script>