<div class="timeline-container" data-app="search">
	<div class="timeline-header">
		<div class="lp">
			<div class="nav-link-holder">
				<a href="<?php echo cl_link("search"); ?>" data-spa="true">
					<?php echo cl_translate("Search"); ?>
				</a>
			</div>
		</div>
		<div class="cp">
			<a href="<?php echo cl_link('/'); ?>">
				<img src="{%config site_logo%}" alt="Logo">
			</a>
		</div>
		<div class="rp">
			<div class="nav-link-holder">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_svg('md-arrow-back'); ?>
				</span>
			</div>
		</div>
	</div>

	<div class="vue-app-body" id="vue-search-app">
		<div class="main--search-form-wrapper">
			<form data-an="search-form" class="form" v-on:submit="search_entries($event)">
				<div class="keyword-input">
					<input v-on:input="search_entries" v-model="search_query" v-bind:disabled="(empty_list == '1')" type="text" placeholder="<?php echo cl_translate("Type a query and press Enter. E.g. #hashtag, username, etc.."); ?>" autofocus="true">

					<span class="search-icon">
						<?php echo cl_svg('md-search'); ?>
					</span>

					<span class="spinner-icon" v-if="searching">
						<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve"><path opacity="0.6" fill="#1ca1f3" d="M20.201,5.169c-8.254,0-14.946,6.692-14.946,14.946c0,8.255,6.692,14.946,14.946,14.946 s14.946-6.691,14.946-14.946C35.146,11.861,28.455,5.169,20.201,5.169z M20.201,31.749c-6.425,0-11.634-5.208-11.634-11.634 c0-6.425,5.209-11.634,11.634-11.634c6.425,0,11.633,5.209,11.633,11.634C31.834,26.541,26.626,31.749,20.201,31.749z"></path><path fill="#1ca1f3" d="M26.013,10.047l1.654-2.866c-2.198-1.272-4.743-2.012-7.466-2.012h0v3.312h0 C22.32,8.481,24.301,9.057,26.013,10.047z" transform="rotate(299.57 20 20)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 20 20" to="360 20 20" dur="0.7s" repeatCount="indefinite"></animateTransform></path></svg>
					</span>
				</div>
			</form>
		</div>

		<div class="main--search-area-navbar">
			<a v-bind:href="search_htags_url" data-spa="true">
				<button class="navbar-item-btn <?php if($cl["page_tab"] == "htags") { echo("active");} ?>">
					<?php echo cl_translate("Hashtags"); ?>
				</button>
			</a>
			<a v-bind:href="search_people_url" data-spa="true">
				<button class="navbar-item-btn <?php if($cl["page_tab"] == "people") { echo("active");} ?>">
					<?php echo cl_translate("People"); ?>
				</button>
			</a>
			<a v-bind:href="search_posts_url" data-spa="true">
				<button class="navbar-item-btn <?php if($cl["page_tab"] == "posts") { echo("active");} ?>">
					<?php echo cl_translate("Posts"); ?>
				</button>
			</a>
		</div>

		<div class="main--search-area-content">
			<div class="search-result-container">
				<?php if (empty($cl["query_result"]) && empty($cl["search_query"])): ?>
					<?php echo cl_template('search/includes/empty_list'); ?>
				<?php else: ?>
					<?php echo cl_template(cl_strf('search/includes/%s',$cl["page_tab"])); ?>
					<?php echo cl_template('search/includes/empty_result'); ?>
				<?php endif; ?>
			</div>
			<div class="load-more" v-if="show_loader">
				<button v-if="loading_more" class="btn btn-custom main-outline lg" disabled="true">
					<?php echo cl_translate("Please wait"); ?>
				</button>
				<button v-else-if="load_more" class="btn btn-custom main-outline lg" v-on:click="load_entries($event)">
					<?php echo cl_translate("Show more"); ?>
				</button>
				<button v-else class="btn btn-custom main-outline lg" disabled="true">
					<?php echo cl_translate("That is all for now!"); ?>
				</button>
			</div>
		</div>
	</div>

	<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
	<?php echo cl_template('search/scripts/app_master_script'); ?>
</div>