<div class="timeline-container">
	<div class="timeline-container-inner">
		<div class="timeline-header">
			<div class="lp">
				<div class="nav-link-holder">
					<a href="<?php echo cl_link('chats'); ?>" data-spa="true">
						<?php echo cl_translate('Messages'); ?>
					</a> 
				</div>
			</div>
			<div class="cp">
				<a href="<?php echo cl_link('/'); ?>">
					<img src="{%config site_logo%}" alt="Logo">
				</a>
			</div>
			<div class="rp">
				<div class="nav-link-holder">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_svg('md-arrow-back'); ?>
					</span>
				</div>
			</div>
		</div>

		<div class="vue-app-body" id="vue-chats-app">
			<div class="vue-app-body-inner">
				<div class="chat--search-form-wrapper">
					<form class="form">
						<div class="keyword-input">
							<input v-model="search_query" v-on:input="search_chats($event)" type="text" placeholder="<?php echo cl_translate('Search for contacts, enter username..'); ?>">
							<span class="icon">
								<?php echo cl_svg('md-search'); ?>
							</span>
							<span v-if="searching" class="spinner-icon" v-if="search_inquiries">
								<?php echo cl_svg('spinner-icon'); ?>
							</span>
						</div>
					</form>
				</div>

				<div class="chat--contacts-list-wrapper">
					<?php if (not_empty($cl["chats"])): ?>
						<div v-show="display_chats" class="chat--contacts-list" data-an="contacts-list">
							<?php foreach ($cl["chats"] as $cl['li']): ?>
								<?php echo cl_template('chats/includes/list_item'); ?>
							<?php endforeach; ?>
						</div>
						<div v-show="(display_chats != true)" class="empty-search-result">
							<div class="icon">
								<?php echo cl_svg('search-circle-outline'); ?>
							</div>
							<div class="pl-message">
								<h4>
									<?php echo cl_translate("Nothing found!"); ?>
								</h4>
								<p>
									<?php echo cl_translate("Could not find anything in your chats history for your search query {@search_query@}. Please try again by typing other keywords.", array(
										"search_query" => cl_html_el('b', '{{search_query}}', array('class' => 'seach-query'))
									)); ?>
								</p>
							</div>
						</div>
					<?php else: ?>
						<div class="empty-chats-list">
							<div class="icon">
								<?php echo cl_svg('chatbubbles-outline'); ?>
							</div>
							<div class="pl-message">
								<h4>
									<?php echo cl_translate("No chats yet!"); ?>
								</h4>
								<p>
									<?php echo cl_translate("Oops! It looks like you don't have any chat history yet. To start chatting with a user, open his profile page, then click on the button with {@svg_icon@} to start chatting",array(
										"svg_icon" => cl_strf('<span><svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><title>ionicons-v5-l</title><path d="M431,320.6c-1-3.6,1.2-8.6,3.3-12.2a33.68,33.68,0,0,1,2.1-3.1A162,162,0,0,0,464,215c.3-92.2-77.5-167-173.7-167C206.4,48,136.4,105.1,120,180.9a160.7,160.7,0,0,0-3.7,34.2c0,92.3,74.8,169.1,171,169.1,15.3,0,35.9-4.6,47.2-7.7s22.5-7.2,25.4-8.3a26.44,26.44,0,0,1,9.3-1.7,26,26,0,0,1,10.1,2L436,388.6a13.52,13.52,0,0,0,3.9,1,8,8,0,0,0,8-8,12.85,12.85,0,0,0-.5-2.7Z" style="fill:none;stroke-linecap:round;stroke-miterlimit:10;stroke-width:32px"/><path d="M66.46,232a146.23,146.23,0,0,0,6.39,152.67c2.31,3.49,3.61,6.19,3.21,8s-11.93,61.87-11.93,61.87a8,8,0,0,0,2.71,7.68A8.17,8.17,0,0,0,72,464a7.26,7.26,0,0,0,2.91-.6l56.21-22a15.7,15.7,0,0,1,12,.2c18.94,7.38,39.88,12,60.83,12A159.21,159.21,0,0,0,284,432.11" style="fill:none;stroke-linecap:round;stroke-miterlimit:10;stroke-width:32px"/></svg></span>')
									)); ?>
								</p>
							</div>
							<div class="c2action-single">
								<a href="<?php echo cl_link('/'); ?>" data-spa="true">
									<button class="btn btn-custom main-outline lg">
										<?php echo cl_translate("Go to the homepage"); ?>
									</button>
								</a>
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
		<?php echo cl_template('chats/scripts/app_master_script'); ?>
	</div>
</div>

