<div class="cp-app-container" data-app="changelogs">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                <?php echo cl_translate('Changelogs'); ?>
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        <?php echo cl_translate('Control panel'); ?>
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        <?php echo cl_translate('Changelogs'); ?>
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.7 (<time>08 October 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Emergency updates due to previous bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.6 (<time>20 September 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] SPA loading system (No hard refreshes anyomore)</p>
                    <p>- [Added] Ads system</p>
                    <p>- [Added] Affiliate system</p>
                    <p>- [Added] User wallet system</p>
                    <p>- [Added] User reporting system</p>
                    <p>- [Added] User block/unblock system</p>
                    <p>- [Added] Link OG data fetching system</p>
                    <p>- [Added] Media uploading progress bar system</p>
                    <p>- [Added] Emoji support to the chat system (Only for desktop browsers)</p>
                    <p>- [Improved] Post-media preloaders</p>
                    <p>- [Improved] Post #htags displaying system</p>
                    <p>- [Improved] User follow suggestion system</p>
                    <p>- [Fixed] Issue with domains (www)</p>
                    <p>- [Fixed] Issue with links to post on social media (Facebook, etc.)</p>
                    <p>- [Fixed] Other minor issues with the script</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.5 (<time>15 July 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] User verification system</p>
                    <p>- [Added] Registration confirmation system</p>
                    <p>- [Added] User ban by admin system</p>
                    <p>- [Added] User privacy system</p>
                    <p>- [Added] Welcome page for guests</p>
                    <p>- [Added] Media files (Images, Videos) lazy loading system</p>
                    <p>- [Added] Sitemap creation system</p>
                    <p>- [Fixed] Previous several minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.4 (<time>29 June 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous several minor bugs (URLs in posts, image extentions support, etc..)</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.3 (<time>15 June 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Feature] function for changing the username specified during registration</p>
                    <p>- [Fixed] bug with drop-down menu on profile settings page</p>
                    <p>- [Fixed] bug with pop-up message on the home page</p>
                    <p>- [Fixed] bug with function of display language for the user</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.2 (<time>11 June 2020</time>) [Emergency update for bug fixes]
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] bug with user gender difference (His/Her) In timeline</p>
                    <p>- [Fixed] bug with dropdown menu For mobile devices</p>
                    <p>- [Fixed] bug moving cover on user profile page</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.1 (<time>30 May 2020</time>) [Emergency update for bug fixes]
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous several important bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.0 (<time>21 May 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- Version 1.0.0 released on 21 May 2020.</p>
                </div>
            </div>
        </div>
    </div>
</div>
