<div class="suggested-list-item">
	<div class="avatar">
		<img src="<?php echo($cl['li']['avatar']); ?>" alt="Avatar">
	</div>
	<div class="user-info-holder">
		<h4>
			<span class="user-name-holder <?php if ($cl['li']['verified'] == '1') {echo('verified-badge');} ?>">
				<?php echo cl_croptxt($cl['li']['name'], 15, '..'); ?>
			</span>
		</h4>
		<a href="<?php echo($cl['li']['url']); ?>" data-spa="true">
			<?php echo($cl['li']['username']); ?>
		</a>
		<?php if (not_empty($cl['li']['about'])): ?>
			<p>
				<?php echo cl_croptxt($cl['li']['about'], 120, '..'); ?>
			</p>
		<?php endif; ?>

		<button onclick="SMColibri.follow(this);" class="btn btn-custom md main-outline" data-action="follow" data-id="<?php echo($cl['li']['id']); ?>">
			<?php echo cl_translate("Follow"); ?>
		</button>
	</div>
</div>