<div class="cp-app-container" data-app="affiliate-payouts">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                <?php echo cl_translate('Affiliate payouts'); ?>
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        <?php echo cl_translate('Control panel'); ?>
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        <?php echo cl_translate('Affiliate payouts'); ?>
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card" id="vue-cpanel-affiliate-payouts-app" data-an="info-content">
                <div class="header">
                    <h2>
                        <?php echo cl_translate('Manage affiliate payout requests'); ?> - ({{total_requests}})
                    </h2>
                </div>
                <div class="body">
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox info">
                            <div class="icon">
                                <i class="material-icons">info</i>
                            </div>
                            <div class="alert-message">
                                <p>
                                    <?php echo cl_translate('Please note: When paying or refusing to pay, do not forget to send a notification to the user by email, informing him about the result of his request.'); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        <?php echo cl_translate('Username'); ?>
                                    </th>
                                    <th>
                                        <?php echo cl_translate('E-mail address'); ?>
                                    </th>
                                    <th>
                                        <?php echo cl_translate('Paypal'); ?>
                                    </th>
                                    <th>
                                        <?php echo cl_translate('Amount'); ?>
                                    </th>
                                    <th>
                                        <?php echo cl_translate('Status'); ?>
                                    </th>
                                    <th>
                                        <?php echo cl_translate('Requested at'); ?>
                                    </th>
                                    <th>
                                        <?php echo cl_translate('Action'); ?>
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="requests-list">
                                <?php if (not_empty($cl['requests'])): ?>
                                    <?php foreach ($cl['requests'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/affiliate_payouts/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="8">
                                            <div class="empty-table">
                                                <span class="icon">
                                                    <i class="material-icons">group_work</i>
                                                </span>
                                                <h4><?php echo('No requests found'); ?></h4>
                                                <p>
                                                    <?php echo('It looks like there are no affiliate payout requests in your database yet. All affiliate payout requests will be displayed here.'); ?>
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>

                        <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}" v-on:click="paginate('up')" href="javascript:void(0);" class="pagination-ctrls prev">
                            <i class="material-icons">chevron_left</i>
                        </a>

                        <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}" v-on:click="paginate('down')" href="javascript:void(0);" class="pagination-ctrls next">
                            <i class="material-icons">chevron_right</i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo cl_template('cpanel/assets/affiliate_payouts/scripts/app_master_script'); ?>