<script>
	
	"use strict";

	$(document).ready(function($) {

		<?php echo cl_js_template('apps/timeline/scripts/js/pubbox_mixin'); ?>
		
		if ($("form#vue-pubbox-app-2").length) {
			var pubbox_app_2 = new Vue({
				el:"#vue-pubbox-app-2",
				mixins: [pubbox_form_app_mixin]
			});

			$(pubbox_app_2.$el).find('textarea#post-text').emojioneArea({
				pickerPosition: "bottom",
				search: false,
				filters: emoji_filters
			});

			$(pubbox_app_2.$el).find('textarea#post-text').get(0).emojioneArea.on('emojibtn.click', function(event) {
				pubbox_app_2.text = $(pubbox_app_2.$el).find('textarea#post-text').get(0).emojioneArea.getText();
			});

			$(pubbox_app_2.$el).find('textarea#post-text').get(0).emojioneArea.on('keyup', function(event) {
				pubbox_app_2.text = $(pubbox_app_2.$el).find('textarea#post-text').get(0).emojioneArea.getText();
			});

			SMColibri.extend_vue('pubbox2', pubbox_app_2);

			$(document).on('hidden.bs.modal','div#add_new_post', function () {  
		        pubbox_app_2.thread_id = 0;
		    });
		}
	});
</script>